Repository iotaledger/common-rs, pull requests merged in 2022-02, with the labels that each got.

#15 derive `Error` under the `std` feature for `packable` error types
  packable/packable/CHANGELOG.md
  packable/packable/Cargo.toml
  packable/packable/src/error.rs
  packable/packable/src/lib.rs
  packable/packable/src/packable/bounded.rs
  packable/packable/src/packable/option.rs
  packable/packable/src/packable/prefix.rs
Labels: c-enhancement, e-medium, p-medium

#18 implement `Packable` for `f32` and `f64`
  packable/packable/CHANGELOG.md
  packable/packable/src/packable/mod.rs
  packable/packable/src/packable/num.rs
  packable/packable/tests/common/mod.rs
  packable/packable/tests/integer.rs
  packable/packable/tests/num.rs
Labels: c-feature, e-medium, p-medium

#17 implement `Packable` for `usize`, `isize`, `Vec<T>`, `Box<[T]>` and `String`
  packable/packable/CHANGELOG.md
  packable/packable/Cargo.toml
  packable/packable/src/packable/box.rs
  packable/packable/src/packable/mod.rs
  packable/packable/src/packable/num.rs
  packable/packable/src/packable/string.rs
  packable/packable/src/packable/vec.rs
  packable/packable/tests/boxed_slice.rs
  packable/packable/tests/num.rs
  packable/packable/tests/string.rs
  packable/packable/tests/vec.rs
Labels: c-feature, e-medium, p-medium

#19 Do some quality of life changes to `packable` error types
  packable/packable/CHANGELOG.md
  packable/packable/src/error.rs
  packable/packable/src/packable/prefix.rs
  packable/packable/src/packable/string.rs
Labels: c-cleanup, e-high, p-low

#20 Update `packable` documentation
  .github/workflows/ci.yml
  packable/packable/README.md
  packable/packable/src/lib.rs
  packable/packable/src/packable/mod.rs
Labels: c-documentation, e-high, p-low

#21 Bump packable version to 0.2
  packable/packable-derive-test/Cargo.toml
  packable/packable-derive/Cargo.toml
  packable/packable/CHANGELOG.md
  packable/packable/Cargo.toml
Labels: c-documentation, e-low, p-low

#10 Add tokio `console` subscriber layer to `trace-tools`
  fern-logger/CHANGELOG.md
  fern-logger/Cargo.toml
  fern-logger/src/config.rs
  trace-tools/trace-tools/.cargo/config.toml
  trace-tools/trace-tools/CHANGELOG.md
  trace-tools/trace-tools/Cargo.toml
  trace-tools/trace-tools/README.md
  trace-tools/trace-tools/examples/console.rs
  trace-tools/trace-tools/src/error.rs
  trace-tools/trace-tools/src/subscriber/layer/flamegraph.rs
  trace-tools/trace-tools/src/subscriber/layer/log.rs
  trace-tools/trace-tools/src/subscriber/layer/mod.rs
  trace-tools/trace-tools/src/subscriber/mod.rs
Labels: c-enhancement, e-high, p-medium

#27 Derive PartialEq for logger config builders
  fern-logger/CHANGELOG.md
  fern-logger/Cargo.toml
  fern-logger/src/config.rs
  trace-tools/trace-tools/CHANGELOG.md
  trace-tools/trace-tools/Cargo.toml
Labels: c-enhancement, e-low, p-medium
